# Copyright (c) 2024-2025 Hopsworks AB. All rights reserved.

apiVersion: v2
name: rondb

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.6.14

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 22.10.12-0.7

# kubeVersion: A SemVer range of compatible Kubernetes versions (optional)
kubeVersion: ">= 1.27.0-0"

description: A Helm chart for RonDBCluster
type: application
keywords:
  - RonDB
  - Database
  - Distributed
  - LATS
  - MySQL
  - Hopsworks
home: https://www.rondb.com
sources:
  - https://github.com/logicalclocks/rondb
  - https://github.com/logicalclocks/rondb-docker
  - https://github.com/logicalclocks/rondb-helm
maintainers:
  - name: Vincent Lohse
    email: vincent.lohse@hopsworks.ai
    url: https://github.com/olapiv
icon: https://uploads-ssl.webflow.com/6013cab68382f702f5481fa8/621f2f69a834b6df8d52cf75_Logo%20-%20Yellow%2C%20on%20black%20BG%404x.png
deprecated: false
# annotations:
#   example: A list of annotations keyed by name (optional).

dependencies: []
