clusterSize:
  activeDataReplicas: 2
  numNodeGroups: 1
  minNumMySQLServers: 2
  maxNumMySQLServers: 1
  minNumRdrs: 1
  maxNumRdrs: 1

resources:
  limits:
    cpus:
      mgmds: 0.2
      ndbmtds: 2
      mysqlds: 2
      rdrs: 2
      benchs: 2
    memory:
      mgmds: 50M
      ndbmtds: 3100M
      mysqlds: 1400M
      rdrs: 500M
      benchs: 500M
  requests:
    cpus:
      mgmds: 0.2
      ndbmtds: 1
      mysqlds: 1
      rdrs: 1
      benchs: 1
    memory:
      mgmds: 20M
      ndbmtds: 2000M
      mysqlds: 650M
      rdrs: 100M
      benchs: 100M

rondbConfig:
  NumCPUs: 4
  TotalMemoryConfig: 2900M
  MaxNoOfTables: 384
  MaxNoOfAttributes: 8000
  MaxNoOfTriggers: 4000
  TransactionMemory: 300M
  SharedGlobalMemory: 300M
  ReservedConcurrentOperations: 50000
  FragmentLogFileSize: 128M
  MaxNoOfConcurrentOperations: 200000

  EmptyApiSlots: 0
  MySQLdSlotsPerNode: 4
  RdrsSlotsPerNode: 2

benchmarking:
  dbt2:
    numWarehouses: 4
    runSingle: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      1                    1               1
      1                    2               1
      1                    4               1
      1                    4               2
    runMulti: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      2                    1               1
      2                    2               1
      2                    2               2
  sysbench:
    threadCountsToRun: "1;2;4;8;12;16;24;32"
    rows: 100000
