isMultiNodeCluster: true

clusterSize:
  activeDataReplicas: 2
  numNodeGroups: 1
  minNumMySQLServers: 2
  maxNumMySQLServers: 2
  minNumRdrs: 1
  maxNumRdrs: 1

resources:
  limits:
    cpus:
      mgmds: 0.2
      ndbmtds: 2
      mysqlds: 2
      rdrs: 2
      benchs: 2
    memory:
      ndbmtdsMiB: 3500
      rdrsMiB: 500
      benchsMiB: 500
  requests:
    cpus:
      mgmds: 0.2
      ndbmtds: 1
      mysqlds: 1
      rdrs: 1
      benchs: 1
    memory:
      ndbmtdsMiB: 3300
      rdrsMiB: 100
      benchsMiB: 100
    storage:
      diskColumnGiB: 4
      redoLogGiB: 4
      undoLogsGiB: 4

rondbConfig:
  NumCPUs: 4
  MaxNoOfTables: 384
  MaxNoOfAttributes: 8000
  MaxNoOfTriggers: 4000
  TransactionMemory: 300M
  SharedGlobalMemory: 300M
  ReservedConcurrentOperations: 50000
  MaxNoOfConcurrentOperations: 200000

  EmptyApiSlots: 0
  MySQLdSlotsPerNode: 4
  RdrsSlotsPerNode: 2

benchmarking:
  dbt2:
    numWarehouses: 4
    runSingle: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      1                    1               1
      1                    2               1
      1                    4               1
      1                    4               2
    runMulti: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      2                    1               1
      2                    2               1
      2                    2               2
  sysbench:
    threadCountsToRun: "1;2;4;8;12;16;24;32"
    rows: 100000
