isLocalCluster: false

# TODO: Consider using Chart.appVersion for tag instead
image:
  registry: docker.io/hopsworks
  tag: 22.10.1-0.4

mysql:
  rootPassword: "Abc123?eeee"
  sqlInitContent: |
    CREATE TABLE IF NOT EXISTS ycsb.usertable (
        YCSB_KEY VARCHAR(255) PRIMARY KEY,
        FIELD0 varbinary(4096)
    );

clusterSize:
  activeDataReplicas: 1
  numNodeGroups: 1
  minNumMySQLServers: 1
  maxNumMySQLServers: 5
  minNumRdrs: 1
  maxNumRdrs: 2

resources:
  limits:
    cpus:
      mgmds: 0.2
      ndbmtds: 2
      mysqlds: 2
      rdrs: 2
      benchs: 2
    memory:
      mgmds: 50M
      ndbmtds: 3300M
      mysqlds: 1400M
      rdrs: 500M
      benchs: 500M
  requests:
    cpus:
      mgmds: 0.2
      ndbmtds: 1
      mysqlds: 1
      rdrs: 1
      benchs: 1
    memory:
      mgmds: 20M
      ndbmtds: 2300M
      mysqlds: 650M
      rdrs: 100M
      benchs: 100M
    storage:
      mgmdData: 10Mi
      mgmdLogs: 20Mi
      ndbmtdData: 1Gi
      ndbmtdLogs: 1Gi

rondbConfig:
  NumCPUs: 4
  TotalMemoryConfig: 3100M
  MaxNoOfTables: 384
  MaxNoOfAttributes: 8000
  MaxNoOfTriggers: 4000
  TransactionMemory: 300M
  SharedGlobalMemory: 300M
  ReservedConcurrentOperations: 50000
  FragmentLogFileSize: 128M
  MaxNoOfConcurrentOperations: 200000

  EmptyApiSlots: 8
  MySQLdSlotsPerNode: 4
  RdrsSlotsPerNode: 2

benchmarking:
  enabled: false
  mysqlUsername: "bench"
  mysqlPassword: "Abc123?e"
  type: "sysbench"
  dbt2:
    numWarehouses: 4
    runSingle: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      1                    1               1
      1                    2               1
      1                    4               1
      1                    4               2
    runMulti: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      2                    1               1
      2                    2               1
      2                    2               2
  sysbench:
    threadCountsToRun: "1;2;4;8;12;16;24;32;64"
    rows: 100000
