# Copyright (c) 2024-2024 Hopsworks. All rights reserved.

meta:
  mgmd:
    statefulSetName: mgmds
    headlessClusterIp:
      name: headless-mgmds
      port: 1186
      annotations: {}
  mysqld:
    statefulSet:
      name: mysqlds
      endToEndTls:
        enabled: false
        secretName: mysqld-end-to-end-tls
        supplyOwnSecret: false
        certfileName: tls.crt
        keyfileName: tls.key
        cafileName: null
    clusterIp:
      name: mysqld
      port: 3306
      annotations: {}
    headlessClusterIp:
      name: headless-mysqlds
      port: 3306
    externalLoadBalancer:
      name: mysqld-external
      enabled: false
      class: null
      annotations: {}
      port: 3306
    exporter:
      metricsPort: 9104
    addSysNiceCapability: true
  binlogServers:
    statefulSet:
      name: mysqld-binlog-servers
      endToEndTls:
        enabled: false
        secretName: binlog-end-to-end-tls
        supplyOwnSecret: false
        certfileName: tls.crt
        keyfileName: tls.key
        cafileName: null
    headlessClusterIp:
      name: headless-binlog-servers
      port: 3306
    # One LoadBalancer per binlog server; Creating an Ingress per binlog server is difficult
    externalLoadBalancers:
      namePrefix: binlog-server
      enabled: true
      class: null
      annotations: {}
      port: 3306
  replicaAppliers:
    statefulSet:
      name: mysqld-replica-appliers
      endToEndTls:
        enabled: false
        secretName: replica-applier-end-to-end-tls
        supplyOwnSecret: false
        certfileName: tls.crt
        keyfileName: tls.key
        cafileName: null
    headlessClusterIp:
      name: headless-replica-appliers
      port: 3306
  rdrs:
    statefulSet:
      name: rdrs
      endToEndTls:
        enabled: false
        secretName: rdrs-end-to-end-tls
        supplyOwnSecret: false
        certfileName: tls.crt
        keyfileName: tls.key
        cafileName: null
    clusterIpName: rdrs
    headlessClusterIpName: rdrs-cluster-ip
    annotations:
      consul.hashicorp.com/service-name: rdrs
      prometheus.io/path: "/metrics"
      prometheus.io/port: "4406"
      prometheus.io/scheme: "https"
      prometheus.io/scrape: "true"
    externalLoadBalancer:
      name: rdrs-external
      enabled: false
      class: null
      annotations: {}
    ingress:
      enabled: false
      class: nginx
      useDefaultBackend: true
      dnsNames:
      - rondb.com
      tls:
        enabled: true
        ipAddresses:
        - 127.0.0.1
staticCpuManagerPolicy: false
isMultiNodeCluster: true
terminationGracePeriodSeconds: 60
priorityClass: rondb-high-priority
enableSecurityContext: true
serviceAccountAnnotations: {}
networkPolicy:
  mgmds:
    enabled: true
    ingressSelectors: []
  ndbmtds:
    enabled: true
    ingressSelectors: []
imagePullSecrets: []
imagePullPolicy: IfNotPresent
# TODO: Consider using Chart.appVersion for tag instead
images:
  rondb:
    registry: docker.io
    repository: hopsworks
    name: rondb
    tag: latest
  toolbox:
    registry: docker.io
    repository: hopsworks
    name: hwutils
    tag: "0.5"
  dataValidation:
    registry: docker.io
    repository: ""
    name: python
    tag: 3.12-slim
  mysqldExporter:
    registry: docker.hops.works
    repository: hopsworks
    name: mysqld_exporter
    tag: 0.11.2
mysql:
  credentialsSecretName: "mysql-passwords"
  clusterUser: "helm"
  sqlInitContent: {}
  supplyOwnSecret: false
  exporter:
    enabled: false
    username: "exporter"
    maxUserConnections: 3
  users:
  - username: hopsworksroot
    host: "%"
    privileges:
      - database: "*"
        tables:
          "*":
            - "ALL"
clusterSize:
  activeDataReplicas: 1
  numNodeGroups: 1
  minNumMySQLServers: 1
  maxNumMySQLServers: 5
  minNumRdrs: 1
  maxNumRdrs: 2
resources:
  limits:
    cpus:
      mgmds: 0.2
      ndbmtds: 2
      mysqlds: 2
      rdrs: 2
      benchs: 2
      restore: 1
      mysqldExporters: 0.2
    memory:
      ndbmtdsMiB: 4500
      rdrsMiB: 500
      mysqldMiB: 1400
      benchsMiB: 500
      mysqldExportersMiB: 100
  requests:
    cpus:
      mgmds: 0.2
      mysqlds: 1
      rdrs: 1
      benchs: 1
      mysqldExporters: 0.02
    memory:
      rdrsMiB: 100
      mysqldMiB: 650
      benchsMiB: 100
      mysqldExportersMiB: 50
    storage:
      classes:
        default: null
        diskColumns: null
        binlogFiles: null
      diskColumnGiB: 2
      redoLogGiB: 2
      undoLogsGiB: 2
      slackGiB: 1
      logGiB: 2
      binlogGiB: 2
      relayLogGiB: 2
rondbConfig:
  EmptyApiSlots: 8
  MySQLdSlotsPerNode: 4
  RdrsSlotsPerNode: 1
  RdrsMetadataSlotsPerNode: 1
  NdbmtdMemoryOverheadMiB: 1024
  InitialTablespaceSizeGiB: -1
rdrs:
  externalMetadataCluster:
    slotsPerNode: 1
    mgmds: []
tls:
  caSecretName: null
# Using minutes for easier template addition
timeoutsMinutes:
  singleSetupMySQLds: 5
  # TODO: Make this dependent on amount of data
  restoreNativeBackup: 120
benchmarking:
  enabled: false
  type: "sysbench"
  dbt2:
    numWarehouses: 4
    runSingle: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      1                    1               1
      1                    2               1
      1                    4               1
      1                    4               2
    runMulti: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      2                    1               1
      2                    2               1
      2                    2               2
  sysbench:
    threadCountsToRun: "1;2;4;8;12;16;24;32;64"
    rows: 100000
    minimizeBandwidth: false
  ycsb:
    schemata: |
      CREATE TABLE IF NOT EXISTS ycsb.usertable (
          YCSB_KEY VARCHAR(255) PRIMARY KEY,
          FIELD0 varbinary(4096)
      );
restoreFromBackup:
  backupId: null
  pathPrefix: rondb_backup
  excludeDatabases: []
  excludeTables: []
  objectStorageProvider: s3
  s3:
    provider: "AWS"
    endpoint: null
    keyCredentialsSecret:
      name: aws-credentials
      key: key_id
    secretCredentialsSecret:
      name: aws-credentials
      key: access_key
    bucketName: rondb-helm
    region: eu-north-1
    # possible values: aws:kms, aws:kms:dsse, AES256
    serverSideEncryption: aws:kms
backups:
  enabled: false
  pathPrefix: rondb_backup
  schedule: "0 3 * * mon"
  objectStorageProvider: s3
  s3:
    provider: "AWS"
    endpoint: null
    keyCredentialsSecret:
      name: aws-credentials
      key: key_id
    secretCredentialsSecret:
      name: aws-credentials
      key: access_key
    bucketName: rondb-helm
    region: eu-north-1
    # possible values: aws:kms, aws:kms:dsse, AES256
    serverSideEncryption: aws:kms
nodeSelector:
  mysqld: {}
  ndbmtd: {}
  mgmd: {}
  rdrs: {}
  backup: {}
tolerations:
  mysqld: []
  ndbmtd: []
  mgmd: []
  rdrs: []
  backup: []
globalReplication:
  clusterNumber: 1
  primary:
    enabled: false
    numBinlogServers: 2
    maxNumBinlogServers: 2
    expireBinlogsDays: 1.5
    logReplicaUpdates: false
    binlogFilename: binlog
    ignoreDatabases: []
    ignoreTables: []
  secondary:
    enabled: false
    replicateFrom:
      clusterNumber: 2
      useTlsConnection: false
      binlogServerHosts: []
      ignoreDatabases: []
      ignoreTables: []
