meta:
  mysqld:
    headlessClusterIpName: mysqld-cluster-ip
    statefulSetName: mysqlds
    loadBalancerName: mysqld
  rdrs:
    statefulSetName: rdrs
    headlessClusterIpName: rdrs-cluster-ip
    clusterIpName: rdrs

isMultiNodeCluster: false
terminationGracePeriodSeconds: 60

# TODO: Consider using Chart.appVersion for tag instead
image:
  registry: docker.io
  tag: 22.10.1-0.4

mysql:
  sqlInitContent: |
    CREATE TABLE IF NOT EXISTS ycsb.usertable (
        YCSB_KEY VARCHAR(255) PRIMARY KEY,
        FIELD0 varbinary(4096)
    );
  rootCredentialsSecret:
    name: "mysql-passwords"
    key: "root"

  service:
    annotations:
      consul.hashicorp.com/service-name: mysql
      consul.hashicorp.com/service-tags: onlinefs

clusterSize:
  activeDataReplicas: 1
  numNodeGroups: 1
  minNumMySQLServers: 1
  maxNumMySQLServers: 5
  minNumRdrs: 1
  maxNumRdrs: 2

resources:
  limits:
    cpus:
      mgmds: 0.2
      ndbmtds: 2
      mysqlds: 2
      rdrs: 2
      benchs: 2
    memory:
      ndbmtdsMiB: 3800
      rdrsMiB: 500
      mysqldMiB: 1400
      benchsMiB: 500
  requests:
    cpus:
      mgmds: 0.2
      ndbmtds: 1
      mysqlds: 1
      rdrs: 1
      benchs: 1
    memory:
      ndbmtdsMiB: 3500
      rdrsMiB: 100
      mysqldMiB: 650
      benchsMiB: 100
    storage:
      diskColumnGiB: 2
      redoLogGiB: 2
      undoLogsGiB: 2
      slackGiB: 1

rondbConfig:
  NumCPUs: 4
  MaxNoOfTables: 384
  MaxNoOfAttributes: 8000
  MaxNoOfTriggers: 4000
  TransactionMemory: 300M
  SharedGlobalMemory: 300M
  ReservedConcurrentOperations: 50000
  MaxNoOfConcurrentOperations: 200000

  EmptyApiSlots: 8
  MySQLdSlotsPerNode: 4
  RdrsSlotsPerNode: 2

tls:
  ingress:
    enabled: true
    certificateName: rondb-apis-cert
    secretName: rondb-ingress-tls
  endToEnd:
    enabled: false
    mysqld:
      secretName: mysqld-tls
    rdrs:
      secretName: rdrs-tls

benchmarking:
  enabled: false
  mysqlUsername: "bench"
  credentialsSecret:
    name: "mysql-passwords"
    key: "bench"
  type: "sysbench"
  dbt2:
    numWarehouses: 4
    runSingle: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      1                    1               1
      1                    2               1
      1                    4               1
      1                    4               2
    runMulti: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      2                    1               1
      2                    2               1
      2                    2               2
  sysbench:
    threadCountsToRun: "1;2;4;8;12;16;24;32;64"
    rows: 100000
