isLocalCluster: true

clusterSize:
  activeDataReplicas: 2
  numNodeGroups: 1
  minNumMySQLServers: 2
  maxNumMySQLServers: 2
  minNumRdrs: 1
  maxNumRdrs: 1

resources:
  limits:
    cpus:
      mgmds: 0.2
      ndbmtds: 4
      mysqlds: 4
      rdrs: 2
      benchs: 2
    memory:
      ndbmtdsMiB: 8500
      rdrsMiB: 600
      benchsMiB: 600
  requests:
    cpus:
      mgmds: 0.2
      ndbmtds: 4
      mysqlds: 4
      rdrs: 2
      benchs: 1
    memory:
      ndbmtdsMiB: 7300
      rdrsMiB: 100
      benchsMiB: 100
    storage:
      diskColumnGiB: 6
      redoLogGiB: 6
      undoLogsGiB: 6

rondbConfig:
  NumCPUs: 4
  MaxNoOfTables: 384
  MaxNoOfAttributes: 8000
  MaxNoOfTriggers: 4000
  TransactionMemory: 300M
  SharedGlobalMemory: 300M
  ReservedConcurrentOperations: 50000
  MaxNoOfConcurrentOperations: 200000

  EmptyApiSlots: 0
  MySQLdSlotsPerNode: 4
  RdrsSlotsPerNode: 2

benchmarking:
  dbt2:
    numWarehouses: 32
    runSingle: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      1                    1               1
      1                    2               1
      1                    4               1
      1                    6               1
      1                    8               1
      1                    12              1
      1                    16              1
      1                    24              1
      1                    32              1
      1                    32              2
    runMulti: |
      # NUM_MYSQL_SERVERS  NUM_WAREHOUSES  NUM_TERMINALS
      2                    1               1
      2                    2               1
      2                    4               1
      2                    6               1
      2                    8               1
      2                    12              1
      2                    16              1
      2                    16              2
  sysbench:
    threadCountsToRun: "1;2;4;8;12;16;24;32;48;64"
    rows: 100000
