{{- if .Values.benchmarking.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: benchs
  namespace: {{ .Release.Namespace }}
spec:
  parallelism: 1
  backoffLimit: 1
  template:
    spec:
      {{- include "hopsworkslib.imagePullSecrets" . | indent 6 }}
      restartPolicy: OnFailure
      initContainers:
      - name: mysqld-dependency-check
        image: {{ include "image_registry" . }}rondb-standalone:{{ .Values.image.tag }}
        command:
        # Make sure data node has connected to MGMd
        - /bin/bash
        - -c
        - |
          until nslookup $MGMD_HOSTNAME; do
            echo "Waiting for $MGMD_HOSTNAME to be resolvable..."
            sleep $(((RANDOM % 2)+2))
          done

          until nslookup $MYSQLD_LOAD_BALANCER_HOSTNAME; do
            echo "Waiting for $MYSQLD_LOAD_BALANCER_HOSTNAME to be resolvable..."
            sleep $(((RANDOM % 2)+2))
          done

          while true; do
            mysql \
              -h $MYSQLD_LOAD_BALANCER_HOSTNAME \
              --protocol=tcp \
              --port=3306 \
              --user=$MYSQL_BENCH_USER \
              -p"$MYSQL_BENCH_PASSWORD" \
              -e "SELECT 1;"

            if [ $? -eq 0 ]; then
              echo "Successfully connected to MySQL server"
              break
            fi
            echo "MySQL query failed, retrying in a bit..."
            sleep 2
          done
        env:
          - name: MGMD_HOSTNAME
            value: mgmds-0.mgmd.{{ .Release.Namespace }}.svc.cluster.local
          - name: MYSQLD_LOAD_BALANCER_HOSTNAME
            value: mysqld.{{ .Release.Namespace }}.svc.cluster.local
          - name: MYSQL_BENCH_USER
            value: {{ .Values.benchmarking.mysqlUsername }}
          - name: MYSQL_BENCH_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- toYaml .Values.benchmarking.credentialsSecret | nindent 16 }}
      containers:
      - name: bench
        image: {{ include "image_registry" . }}rondb-standalone:{{ .Values.image.tag }}
        command:
        # - Alternatively: 'sleep infinity' for manual tests
        # - If we needed to change hostname & activate API slots, we could
        # do this via the MGM client here using $HOSTNAME.
        - /bin/bash
        - -c
        - |
          set -e
          BENCH_DIR=/home/mysql/benchmarks/{{ .Values.benchmarking.type }}
  
          # Setting passwords in autobench.conf file
          RAW_AUTOBENCH_FILEPATH=$BENCH_DIR/autobench-raw.conf
          AUTOBENCH_FILEPATH=$BENCH_DIR/autobench.conf
          cp $RAW_AUTOBENCH_FILEPATH $AUTOBENCH_FILEPATH
          
          sed -i "/^[ ]*MYSQL_PASSWORD/c\MYSQL_PASSWORD=$MYSQL_BENCH_PASSWORD" $AUTOBENCH_FILEPATH

          set +e
          bench_run.sh \
            --verbose \
            --default-directory $BENCH_DIR
{{- if contains "dbt2" .Values.benchmarking.type }}
            --generate-dbt2-data
{{- end }}

          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            # TODO: Print different files depending on benchmark
            echo "Running benchmark script failed; showing intermediate results"
            cat $BENCH_DIR/sysbench_results/oltp_rw_0_0.res
            exit $exit_code
          else
            cat $BENCH_DIR/final_result.txt
          fi
        env:
          - name: MYSQL_BENCH_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- toYaml .Values.benchmarking.credentialsSecret | nindent 16 }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpus.benchs }}
            memory: {{ .Values.resources.limits.memory.benchsMiB }}Mi
          requests:
            cpu: {{ .Values.resources.requests.cpus.benchs }}
            memory: {{ .Values.resources.requests.memory.benchsMiB }}Mi
        volumeMounts:
        # Not important, but can help to debug benchmarks
        - name: benchmarks
          mountPath: /home/mysql/benchmarks

        - name: benchmark-configs
          mountPath: /home/mysql/benchmarks/sysbench/autobench-raw.conf
          subPath: autobench_sysbench.conf

        - name: benchmark-configs
          mountPath: /home/mysql/benchmarks/dbt2_single/autobench-raw.conf
          subPath: autobench_dbt2.conf
        - name: benchmark-configs
          mountPath: /home/mysql/benchmarks/dbt2_single/dbt2_run_1.conf
          subPath: dbt2_single_run.conf

        - name: benchmark-configs
          mountPath: /home/mysql/benchmarks/dbt2_multi/autobench-raw.conf
          subPath: autobench_dbt2.conf
        - name: benchmark-configs
          mountPath: /home/mysql/benchmarks/dbt2_multi/dbt2_run_1.conf
          subPath: dbt2_multi_run.conf
    ################################################################
    # TODO: Figure out how volumes work when we run benchmarks in parallel
    #       Do they need to be accessed by multiple containers?
    #       If we print the results, the volumes are not needed anymore?
    ################################################################
      volumes:
      - name: benchmarks
        persistentVolumeClaim:
          claimName: benchmarks-claim
      - name: benchmark-configs
        configMap:
          name: benchmark-configs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmarks-claim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: benchmark-configs
  namespace: {{ .Release.Namespace }}
data:
    autobench_sysbench.conf: |
{{ tpl (.Files.Get "files/autobench_sysbench.conf") . | indent 8 }}
    autobench_dbt2.conf: |
{{ tpl (.Files.Get "files/autobench_dbt2.conf") . | indent 8 }}

    dbt2_single_run.conf: |
{{ tpl (.Files.Get "files/dbt2_single_run.conf") . | indent 8 }}
    dbt2_multi_run.conf: |
{{ tpl (.Files.Get "files/dbt2_multi_run.conf") . | indent 8 }}

{{- end -}}
