apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mgmds
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: mgmd
  replicas: 1
  selector:
    # Used by the Deployment to select and manage existing pods with the specified label
    matchLabels:
      rondbService: mgmd
  template:
    metadata:
      # Used to apply labels to all pods created by the Deployment
      labels:
        rondbService: mgmd
    spec:
      containers:
      - name: mgmd
        image: {{ include "image_registry" . }}rondb-standalone:{{ .Values.image.tag }}
        args:
          - ndb_mgmd
          - --ndb-nodeid=65
          - --initial
        ports:
          - containerPort: 1186
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpus.mgmds }}
            memory: {{ .Values.resources.limits.memory.mgmds }}
          requests:
            cpu: {{ .Values.resources.requests.cpus.mgmds }}
            memory: {{ .Values.resources.requests.memory.mgmds }}
        env:
          - name: HOST_GROUP_ID
            value: "0"
        volumeMounts:
        # Only mount single file, otherwise entire directory becomes read-only
        - name: rondb-configs
          mountPath: /srv/hops/mysql-cluster/config.ini
          subPath: config.ini
        - name: rondb-mgmd-data
          mountPath: /srv/hops/mysql-cluster/data
        - name: rondb-mgmd-log
          mountPath: /srv/hops/mysql-cluster/log
      volumes:
      - name: rondb-configs
        configMap:
          name: rondb-configs
      - name: rondb-mgmd-data
        persistentVolumeClaim:
          claimName: rondb-mgmd-data-claim
      - name: rondb-mgmd-log
        persistentVolumeClaim:
          claimName: rondb-mgmd-log-claim
---
apiVersion: v1
kind: Service
metadata:
  # Match the spec.serviceName
  name: mgmd
  namespace: {{ .Release.Namespace }}
spec:
  # Headless service for individual DNS records for the pods
  clusterIP: None
  # Match the spec.template.metadata.labels of the Deployment
  selector:
    rondbService: mgmd
  ports:
    - protocol: TCP
      port: 1186
      targetPort: 1186
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rondb-mgmd-data-claim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.resources.requests.storage.mgmdData }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rondb-mgmd-log-claim
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $.Values.resources.requests.storage.mgmdLogs }}
