apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mgmds
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: mgmd
  replicas: 1
  selector:
    # Used by the Deployment to select and manage existing pods with the specified label
    matchLabels:
      rondbService: mgmd
  volumeClaimTemplates:
    - metadata:
        name: rondb-mgmd-data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 10Mi
    - metadata:
        name: rondb-mgmd-log
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 20Mi
  # Still in beta mode (Jan 2024)
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  template:
    metadata:
      # Used to apply labels to all pods created by the Deployment
      labels:
        rondbService: mgmd
    spec:
{{- include "hopsworkslib.imagePullSecrets" . | indent 6 }}
{{- include "rondb.SecurityContext" $ | indent 6 }}
      containers:
      - name: mgmd
        image: {{ include "image_registry" . }}rondb-standalone:{{ .Values.image.tag }}
        command:
          - /bin/bash
          - -c
          - |
{{ include "entrypoint_mgmd" . | indent 12 }}
        # MGMDs have publishNotReadyAddresses set to false.
        # Adding a readiness probe will therefore have a direct
        # effect on whether other services can reach the MGMd.
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - ndb_mgm -e show
          initialDelaySeconds: 5
          failureThreshold: 3
          periodSeconds: 4
          timeoutSeconds: 2
        # Having a lively MGMd is crucial for other services' healthchecks.
        # Restarting MGMds does not cost much and should be quick.
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - ndb_mgm -e show
          initialDelaySeconds: 5
          failureThreshold: 5
          periodSeconds: 5
          timeoutSeconds: 2
        ports:
          - containerPort: 1186
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpus.mgmds }}
            memory: 100Mi
          requests:
            cpu: {{ .Values.resources.requests.cpus.mgmds }}
            memory: 50Mi
        env:
        volumeMounts:
        # Only mount single file, otherwise entire directory becomes read-only
        - name: rondb-configs
          mountPath: /srv/hops/mysql-cluster/config.ini
          subPath: config.ini
        # This is where the configuration database is stored
        - name: rondb-mgmd-data
          mountPath: /srv/hops/mysql-cluster/mgmd
        - name: rondb-mgmd-log
          mountPath: /srv/hops/mysql-cluster/log
      volumes:
      - name: rondb-configs
        configMap:
          name: rondb-configs
---
apiVersion: v1
kind: Service
metadata:
  # Match the spec.serviceName
  name: mgmd
  namespace: {{ .Release.Namespace }}
spec:
  # Headless service for individual DNS records for the pods
  clusterIP: None
  # Match the spec.template.metadata.labels of the Deployment
  selector:
    rondbService: mgmd
  ports:
    - protocol: TCP
      port: 1186
      targetPort: 1186
