apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.meta.mysqld.statefulSetName }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Values.meta.mysqld.headlessClusterIp.name }}
  replicas: {{ .Values.clusterSize.minNumMySQLServers }}
  selector:
    # Used by the Deployment to select and manage existing pods with the specified label
    matchLabels:
      rondbService: mysqld
  # Still in beta mode (Jan 2024)
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Retain
  template:
    metadata:
      # Used to apply labels to all pods created by the Deployment
      labels:
        rondbService: mysqld
    spec:
      {{- include "hopsworkslib.imagePullSecrets" . | indent 6 }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          # Try to evenly distribute MySQLds between node groups for low latency
          # Risk: Some node groups may receive more MySQLds than others
          - weight: 90
            preference:
              matchExpressions:
              - key: nodeGroup
                operator: In
                values:
{{- range $nodeGroup := until ($.Values.clusterSize.numNodeGroups | int) }}
                - {{ $nodeGroup | quote }}
{{ end }}
        # We want the placement of MySQLds be primarily based on the node groups.
        # The anti-affinities are in place to ensure that the MySQLds are at least
        # spread between node group *replicas*. The risk remains of MySQLds being
        # unevenly distributed between node groups.
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          # Preferred on different node
          - weight: 80
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: rondbService
                  operator: In
                  values:
                  - mysqld
              topologyKey: kubernetes.io/hostname
          # Preferred in different zone for HA
          - weight: 40
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: rondbService
                  operator: In
                  values:
                  - mysqld
              topologyKey: topology.kubernetes.io/zone
{{- include "rondb.SecurityContext" . | indent 6 }}
      initContainers:
      - name: datanode-dependency-check
        image: {{ include "image_address" (dict "image" .Values.images.rondb) }}
        command:
        # Make sure data node has connected to MGMd
        - /bin/bash
        - -c
        - |
          MGMD_HOST={{ .Values.meta.mgmd.statefulSetName }}-0.{{ .Values.meta.mgmd.headlessClusterIp.name }}.{{ .Release.Namespace }}.svc.cluster.local
          until nslookup $MGMD_HOST; do
            echo "Waiting for $MGMD_HOST to be resolvable..."
            sleep $(((RANDOM % 2)+2))
          done

          # Wait until data node is ready
          until ./docker/rondb_standalone/healthcheck.sh $MGMD_HOST:1186 1; do
            echo "Dependency healthcheck of ndbmtd failed. Retrying in a bit"
            sleep $(((RANDOM % 2)+2))
          done
      containers:
      - name: mysqld
        image: {{ include "image_address" (dict "image" .Values.images.rondb) }}
        command:
        - /bin/bash
        - -c
        - |
{{ tpl (.Files.Get "files/entrypoints/mysqlds.sh") . | indent 10 }}
        ports:
          - containerPort: 3306
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpus.mysqlds }}
            memory: {{ .Values.resources.limits.memory.mysqldMiB }}Mi
          requests:
            cpu: {{ .Values.resources.requests.cpus.mysqlds }}
            memory: {{ .Values.resources.requests.memory.mysqldMiB }}Mi
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- toYaml .Values.mysql.rootCredentialsSecret | nindent 16 }}
          - name: MYSQL_BENCH_USER
            value: {{ .Values.benchmarking.mysqlUsername }}
          - name: MYSQL_BENCH_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- toYaml .Values.benchmarking.credentialsSecret | nindent 16 }}
          - name: CONNECTIONS_PER_MYSQLD
            value: {{ .Values.rondbConfig.MySQLdSlotsPerNode | quote}}
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        # This will block liveliness & readiness probes
        # If the startupProbe fails, the pod will be killed
        # The MySQL init takes >20s
        # The MySQL server will first start up with --no-networking
        # During this phase, passwords are initialized. Then it is
        # restarted. Hence, we ping with TCP to make sure it has
        # restarted.
        startupProbe:
          exec:
            command:
              - 'mysqladmin'
              - 'ping'
              - '-uroot'
              - '--protocol=tcp'
{{ if and (not .Values.global) .Values.tls.endToEnd.enabled }}
              - --ssl-mode=REQUIRED
{{ else }}
              - --ssl-mode=PREFERRED
{{ end }}
          initialDelaySeconds: 5
          failureThreshold: 70
          periodSeconds: 1
          timeoutSeconds: 2
        livenessProbe:
          exec:
            command:
              - 'mysqladmin'
              - 'ping'
              - '-uroot'
{{ if and (not .Values.global) .Values.tls.endToEnd.enabled }}
              - --ssl-mode=REQUIRED
{{ else }}
              - --ssl-mode=PREFERRED
{{ end }}
          failureThreshold: 4
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              set -e
              mysql --defaults-file=$RONDB_DATA_DIR/my.cnf \
                -e "SELECT 1"
          failureThreshold: 2
          periodSeconds: 5
          timeoutSeconds: 2
        securityContext:
          capabilities:
            add:
              - SYS_NICE
        volumeMounts:
        # Only mount single file, otherwise entire directory becomes read-only
        - name: rondb-configs
          # Using "raw", so that we can sed NodeIds into the file
          mountPath: /srv/hops/mysql-cluster/my-raw.cnf
          subPath: my.cnf
{{ if .Values.mysql.sqlInitContent }}
        - name: sql-init-script
          mountPath: /srv/hops/docker/rondb_standalone/sql_init_scripts
{{ end }}
      # StatefulSets work with PVCs to create a dedicated persistent volume for
      # each pod replica, ensuring that a pod always re-attaches to the same data
      # even if it is rescheduled to a different node.
{{ if and (not .Values.global) .Values.tls.endToEnd.enabled }}
        - name: tls-certificates
          mountPath: /etc/tls
          readOnly: true
{{- end }}
      volumes:
      - name: rondb-configs
        configMap:
          name: rondb-configs
{{ if .Values.mysql.sqlInitContent }}
      - name: sql-init-script
        configMap:
          name: sql-init-script
{{ end }}
{{ if and (not .Values.global) .Values.tls.endToEnd.enabled }}
      # This will be created by the cert-manager via the Certificate CRD
      # The MySQLd will therefore not start until the certificate is available
      - name: tls-certificates
        secret:
          secretName: {{ .Values.tls.endToEnd.mysqld.secretName }}
          optional: false
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.meta.mysqld.headlessClusterIp.name }}
  namespace: {{ .Release.Namespace }}
spec:
  # Headless service for individual DNS records for the pods
  clusterIP: None
  # So we do not rely on the readiness probe to connect to the MGMd
  publishNotReadyAddresses: true
  # Match the spec.template.metadata.labels of the StatefulSet
  selector:
    rondbService: mysqld
  ports:
    - protocol: TCP
      port: {{ .Values.meta.mysqld.headlessClusterIp.port }}
      targetPort: 3306
---
# This is for
# - the Ingress controller to route traffic to the MySQL server
# - connecting to a MySQLd via Consul
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.meta.mysqld.service.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $k, $v := .Values.meta.mysqld.service.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    rondbService: mysqld
  ports:
  - protocol: TCP
    port: {{ .Values.meta.mysqld.service.port }}
    targetPort: 3306
---
{{ if .Values.mysql.sqlInitContent }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-init-script
  namespace: {{ .Release.Namespace }}
data:
    init.sql: |
{{ include "rondb.sqlInitContent" . | indent 6 }}
---
{{ end }}
{{ if not (eq .Values.clusterSize.minNumMySQLServers .Values.clusterSize.maxNumMySQLServers) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mysqlds
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: {{ .Values.meta.mysqld.statefulSetName }}
  minReplicas: {{ .Values.clusterSize.minNumMySQLServers }}
  maxReplicas: {{ .Values.clusterSize.maxNumMySQLServers }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
{{ end }}
---
{{ if and (not .Values.global) .Values.tls.ingress.enabled }}
# Certificates will prompt the cert-manager to create a TLS Secret using the referenced
# Issuer.
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mysql-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.tls.endToEnd.mysqld.secretName }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - {{ .Values.meta.mysqld.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
    # TODO: this is not needed?
    - {{ .Values.meta.mysqld.headlessClusterIp.name }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
---
{{ end }}
