apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: ndb-high-priority
  namespace: {{ .Release.Namespace }}
value: 1000000
globalDefault: false
description: "This priority class should be used for rondb service pods only."