# Copyright (c) 2024-2025 Hopsworks AB. All rights reserved.

{{/*
    TODO: Add logic to share PriorityClass between multiple charts
*/}}
{{ if .Values.priorityClass -}}
{{- $existingPC := lookup "scheduling.k8s.io/v1" "PriorityClass" "" .Values.priorityClass -}}
{{- $managedByHelm := and $existingPC (eq (index $existingPC.metadata.annotations "meta.helm.sh/release-name" | default "") .Release.Name) -}}
{{- if or (not $existingPC) $managedByHelm }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass }}
value: 1000000
globalDefault: false
description: "This priority class should be used for rondb service pods only."
{{- end  }}
{{- end }}
