apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ $.Values.priorityClass }}
  namespace: {{ $.Release.Namespace }}
description: "This priority class should be used for RonDB service pods only."
value: 1000000
globalDefault: false
