apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqld-configs
  namespace: {{ .Release.Namespace }}
data:
    my.cnf: |
{{ tpl (.Files.Get "files/configs/my.cnf") . | indent 8 }}
    metadata_create.sh: |
{{ tpl (.Files.Get "files/scripts/backups/metadata_create.sh") . | indent 8 }}
