{{- if .Values.mysql.exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rondb
      rondbService: {{ include "rondb.labels.rondbService.mysqld-exporter" $ }}
  template:
    metadata:
      labels:
        app: rondb
        rondbService: {{ include "rondb.labels.rondbService.mysqld-exporter" $ }}
    spec:
{{- include "hopsworkslib.imagePullSecrets" . | indent 6 }}
{{- $global := .Values.global }}
{{- include "hopsworkslib.nodeSelector" (dict "nodeSelector" .Values.nodeSelector.mysqld "global" $global) | indent 6 }}
{{- include "hopsworkslib.tolerations" (dict "tolerations" .Values.tolerations.mysqld "global" $global) | indent 6 }}
      containers:
      - name: mysqld-exporter
        image:  {{ include "image_address" (dict "image" .Values.images.mysqldExporter) }}
        imagePullPolicy: {{ include "hopsworkslib.imagePullPolicy" . | default "IfNotPresent" }}
        {{- include "hopsworkslib.commonContainerSecurityContext" . | nindent 8 }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpus.mysqldExporters }}
            memory: {{ .Values.resources.limits.memory.mysqldExportersMiB }}Mi
          requests:
            cpu: {{ .Values.resources.requests.cpus.mysqldExporters }}
            memory: {{ .Values.resources.requests.memory.mysqldExportersMiB }}Mi
        args:
          - --web.listen-address=:{{ .Values.meta.mysqld.exporter.metricsPort }}
        ports:
          - containerPort: {{ .Values.meta.mysqld.exporter.metricsPort }}
            name: metrics-port
        env:
          - name: MYSQL_USER
            value: {{ .Values.mysql.exporter.username }}
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "rondb.mysql.usersSecretName" . }}
                key: {{ .Values.mysql.exporter.username }}
          - name: MYSQL_HOST
            value: {{ include "rondb.mysqldServiceHostname" . }}
          - name: MYSQL_PORT
            value: {{ .Values.meta.mysqld.service.port | quote }}
          - name: DATA_SOURCE_NAME
            value: "$(MYSQL_USER):$(MYSQL_PASSWORD)@($(MYSQL_HOST):$(MYSQL_PORT))/"
        livenessProbe:
          tcpSocket:
            port: {{ .Values.meta.mysqld.exporter.metricsPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: {{ .Values.meta.mysqld.exporter.metricsPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: rondb
    rondbService: {{ include "rondb.labels.rondbService.mysqld-exporter" $ }}
  annotations:
    prometheus.io/path: '/metrics'
    prometheus.io/port: '{{ .Values.meta.mysqld.exporter.metricsPort }}'
    prometheus.io/scheme: 'http'
    prometheus.io/scrape: 'true'
spec:
  selector:
    app: rondb
    rondbService: {{ include "rondb.labels.rondbService.mysqld-exporter" $ }}
  ports:
    - name: "metrics"
      protocol: TCP
      port: {{ .Values.meta.mysqld.exporter.metricsPort }}
      targetPort: {{ .Values.meta.mysqld.exporter.metricsPort }}
{{- end }}