{{ if not .Values.mysql.supplyOwnSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.mysql.credentialsSecretName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    type: generated-password
{{- $secret := lookup "v1" "Secret" $.Release.Namespace ($.Values.mysql.credentialsSecretName) }}
data:
{{- $users := list
    "root"
    .Values.mysql.clusterUser
}}
{{- if $.Values.mysql.exporter.enabled }}
   {{- $users = append $users $.Values.mysql.exporter.username }}
{{- end }}
{{- range $.Values.mysql.users }}
    {{- $users = append $users .username }}
{{- end }}
{{- range $user := $users}}
{{- if and $secret (index $secret "data" $user) }}
{{ $user | indent 2 }}: {{ index $secret "data" $user | quote }}
{{- else }}
{{ $user | indent 2 }}: {{ randAlphaNum 20 | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
