name: Helm chart development release

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Helm chart
    if: github.repository == 'logicalclocks/rondb-helm'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - run: |
        CHART_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
        echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV

    - name: Publish Helm chart
      uses: ./.github/actions/publish_chart
      with:
        # Helm doesn't support just using "dev"/"latest" as a version
        chart_version: "${{ env.CHART_VERSION }}-dev"
        allow_overwrite: "true"
        gh_token: ${{ secrets.GITHUB_TOKEN }}
