name: Release Charts

on:
  push:
    tags:
      # Semantic versioning; must be equal to version in Chart.yaml
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    name: Publish Helm chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - run: |
        echo "GH ref:       ${{ github.ref }}"
        echo "GH ref_name:  ${{ github.ref_name }}"

    - name: Only allow main branch to publish
      run: |
        branch=$(git branch -r --contains ${{ github.ref }} --format "%(refname:lstrip=3)")
        echo "Current branch: $branch"
        # Exit if branch is not main
        if [ "$branch" != "main" ]; then
          echo "Branch is not main, exiting"
          exit 1
        fi

    - name: Check that Git tag matches Chart.yaml version
      if: github.repository == 'logicalclocks/rondb-helm' && startsWith(github.ref, 'refs/tags/')
      run: |
        TAG=$(echo ${{ github.ref_name }} | sed 's/v//')
        CHART_VERSION=$(grep '^version:' Chart.yaml | awk '{print $2}')
        if [ "$TAG" != "$CHART_VERSION" ]; then
          echo "Tag $TAG does not match Chart.yaml version $CHART_VERSION"
          exit 1
        fi

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
          version: '3.13.3'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    # We're using a simple main branch where every git push tag is the new latest version
    # and we don't overwrite Chart versions.
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        mark_as_latest: true
        pages_branch: gh-pages
        skip_existing: true
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
