name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Helm chart
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
          version: '3.13.3'
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    # We're using a simple main branch where every git push tag is the new latest version
    # and we don't overwrite Chart versions.
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.6.0
      with:
        mark_as_latest: true
        pages_branch: gh-pages
        skip_existing: true
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
